namespace Appalachia.Simulation.Trees.Generation.Texturing.Specifications
{
    public enum TextureMapChannel
    {
        None = 0,
        Albedo_R = 10,
        Albedo_G = 11,
        Albedo_B = 12,
        Normal_TS_X = 20,
        Normal_TS_Y = 21,
        Normal_TS_Z = 22,
        NormalBump_TS_X = 25,
        NormalBump_TS_Y = 26,
        NormalBump_TS_Z = 27,
        Normal_OS_X = 30,
        Normal_OS_Y = 31,
        Normal_OS_Z = 32,
        NormalBump_OS_X = 35,
        NormalBump_OS_Y = 36,
        NormalBump_OS_Z = 37,
        Derivative_X = 40,
        Derivative_Y = 41,
        Displacement = 50,
        Bump = 51,
        AmbientOcclusion = 60,
        Cavity = 61,
        Metallicity = 70,
        Specularity_R = 80,
        Specularity_G = 81,
        Specularity_B = 82,
        Specularity_Strength = 83,
        Glossiness = 90,
        Roughness = 91,
        Opacity = 100,
        Transmission = 110,
        Concavity = 120,
        Convexity = 121,
        Emission_R = 130,
        Emission_G = 131,
        Emission_B = 132,
        AlbedoDetail_BW = 140,
        AlbedoDetail_R = 141,
        AlbedoDetail_G = 142,
        AlbedoDetail_B = 143,
        AlbedoDetail_Opacity = 144,
        DetailMask = 150,
        Shadow = 160,

        Variant_Albedo_R = 510,
        Variant_Albedo_G = 511,
        Variant_Albedo_B = 512,
        Variant_Normal_TS_X = 520,
        Variant_Normal_TS_Y = 521,
        Variant_Normal_TS_Z = 522,
        Variant_Displacement = 550,
        Variant_AmbientOcclusion = 560,
        Variant_Metallicity = 570,
        Variant_Specularity_R = 580,
        Variant_Specularity_G = 581,
        Variant_Specularity_B = 582,
        Variant_Specularity_Strength = 583,
        Variant_Glossiness = 590,
        Variant_Roughness = 591,
        Variant_Opacity = 600,

        SetToZero = 1000,
        SetToPointFive = 1001,
        SetToOne = 1002
    }
}
